# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    # event listener for json response + cors
    api_exception_subscriber:
         class: AppBundle\EventListener\ApiExceptionJson
         arguments: [] #'@service_container', '@jms_serializer'
         tags:
              - { name: kernel.event_subscriber }

    app.file_uploader:
         class: AppBundle\Service\FileUploader
         arguments: ['%upload_path%'] #argument from config/parameter

    #cors response
    joiz_public_api_token.cors.listener:
            class: AppBundle\EventListener\ApiCors
            tags:
                 - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest , priority: 100}
                 - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100}
